version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./server/database:/app/server/database
    depends_on:
      - vectordb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  vectordb:
    image: pgvector/pgvector:pg16
    container_name: vectordb
    environment:
      POSTGRES_USER: ${VECTOR_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${VECTOR_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${VECTOR_DB_NAME:-vectors}
    ports:
      - "5432:5432"
    volumes:
      - vectordb_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - production

volumes:
  vectordb_data: {}